### ISSUE TITLE
DDECal: large fraction of solutions flagged

### ISSUE THREAD

**Issue by darafferty** [lofar-astron/DP3#65] opened 2018-10-16 12:54 UTC
I am testing DDECal (latest master) within Factor (using a single direction), and am getting >99% solutions as flagged (weight = 0). I noticed that the number of iteration is very low. E.g.,

```
Total NDPPP time     106.76 real       84.77 user        0.42 system
   18.9% MSReader
   81.1% DDECal solvetec.
           64.9% of it spent in predict
           34.8% of it spent in estimating gains and computing residuals
                0.29% spent in constraints
            0.0% of it spent in writing gain solutions to disk
Iterations taken: [3|2,4|3,4|3,4|3,4|3,4|3,4|3,4|3,4|3,4|3,4|3,4|3,4|3,4|3,4|3,4|3,4|3,4|3,4|3,4|3,4|3,4|3,4|3,4|3,4|3,4|3,4|3,4|3,4|3,4|3,4|3,4|3,4|3,4|3,4|3,4|3,4|3,4|3,4|3,4|3,4|3,4|3,4|3,4|3,4|3,4|\
3,4|3,4|3,4|3,4|3,4|3,4|3,4|3,4|3,4|3,4|3,4|3,4|3,4|3,4|3,4|3,4|3,4|3,4|3,4|3,4|3,4|3,4|3,4|3,4|3,4|3,4|3,4|3,4|3,4|3,4|3,4|3,4|3,4|3,4|3,4|3,4|3,4|3,4|3,4|3,4|3,4|3,4|3,4|3,4|3,4|3,4|3,4|3,4|3,4|3,4|3\
,4|3,4|3,4|3,4|3,4|3,4|3,4|3,4|3,4|3,4|3,4|3,4|3,4|3,4|3,4|3,4|3,4|3,4|3,4|3,4|3,4|3,4|3,4|3,4|3,4|3,4|3,4|3,4|3,4|3,4|3,4|3,4|3,4|3,4|3,4|3,4|3,4|3,4|3,4|3,4|3,4|3,4|3,4|3,4|3,4|3,4|3,4|3,4|3,4|3,4|3,\
4|3,4|3,4|3,4|3,4|3,4|3,4|3,4|3,4|3,4|3,4|3,4|3,4|3,4|3,4|3,4|3,4|3,4|3,4|3,4|3,4|3,4|3,4|3,4|3,4|3,4|3,4|3,4|3,4|3,4|3,4|3,4|3,4|3,4|3,4|3,4|3,4|3,4|3,4|3,4|3,4|3,4|3,4|3,4|3,4|3,4|3,4|3,4|3,4|3,4|3,4\
|3,4|3,4|3,4|3,4|3,4|3,4|3,4|3,4|3,4|3,4|3,4|3,4|3,4|3,4|3,4|3,4|3,4|3,4|3,4|3,4|3,4|3,4|3,4|3,4|3,4|3,4|3,4|3,4|3,4|3,4|3,4|3,4|3,4|3,4|3,4|3,4|3,4|3,4|3,4|3,4|3,4|3,4|3,4|3,4|3,4|3,4|3,4|3,4|3,4|3,4|\
3,4|3,4|3,4|3,4|3,4|3,4|3,4|3,4|3,4|3,4|3,4|3,4|3,4|3,4|3,4|3,4|3,4|3,4|3,4|3,4|3,4|3,4|3,4|3,4|3,4|3,4|3,4|3,4|3,4|3,4|3,4|3,4|3,4|3,4|3,4|3,4|3,4|3,4|3,4|3,4|3,4|3,4|3,4|3,4|3,4|3,4|3,4|3,4|3,4|3,4|3\
,4|3,4|3,4|3,4|3,4|3,4|3,4|3,4|3,4|3,4|3,4|3,4|3,4|3,4|3,4|3,4|3,4|3,4|3,4|3,4|3,4|3,4|3,4|3,4|3,4|3,4|3,4|3,4|3]
    0.0% MSUpdater msout.
```

I used the following parameters:

```
msin.datacolumn=DATA
msout=.
numthreads=1
solvetec.approximatetec=True
solvetec.detectstalling=False
solvetec.h5parm=h5parm
solvetec.maxapproxiter=50
solvetec.maxiter=75
solvetec.mode=tecandphase
solvetec.nchan=2
solvetec.propagatesolutions=True
solvetec.solint=1
solvetec.sourcedb=sourcedb
solvetec.stepsize=0.2
solvetec.tolerance=1e-05
solvetec.type=ddecal
solvetec.uvlambdamin=80.0
steps=[solvetec]
```

I tried changing the tolerance and stepsize but got similar results. The sourcedb and MS file are at ftp.hs.uni-hamburg.de/pub/outgoing/rafferty in case they're helpful.

**Comment by rvweeren** [comment] 2018-10-16 13:00
I also just noticed this. (this happened in the latest svn trunk version) suggesting the problem already existed for a while. For my August 31 build things work fine. So something happened after that.

**Comment by aroffringa** [comment] 2018-10-18 08:41
Ok that's an issue! I did some changes to how vis weighting are propagated and how convergence is tested, I probably caused a bug there -- because of business & travel, and the large nr of changes to DP3 recently, I haven't always properly tested it. Thanks for the testdata, I'll have a look. For now best to use an older version then?

**Comment by aroffringa** [comment] 2018-10-19 06:19
I've found the issue; it was caused by NaNs in the data that due to some restructuring for #49 were no longer properly set to zero before they were used in calculations. Merge request #67 will solve this, the error was introduced in 8ee62bf3de255acbb59b70108588cbbb7deea97d .

**Comment by tikk3r** [comment] 2018-11-23 13:51
I'm running into the same problem again with the (almost) latest version, commit https://github.com/lofar-astron/DP3/commit/399ea74a71668b5d9f7ef387982f09718633bd14 (Nov. 14), except now with `complexgain`.
`tecandphase` mode seems to work, mostly. Two things are happening:

  - It seems somewhere during a `tecandphase` part all data past 5 hours are flagged (the whole observation is 14 hours)
  - After a subsequent `complexgain` iteration the data is 100% flagged.

The DDECal call for the complex gain part is
```
DPPP msin=NCP-2015-01-20_annoying_source.dysco.sub.shift.avg.weights.ms.correct_shift 
msin.datacolumn=CORRECTED_DATA_PHASE
msout=.
msout.storagemanager=dysco
msin.weightcolumn=WEIGHT_SPECTRUM_SOLVE
msin.modelcolumn=MODEL_DATA
steps=[ddecal]
ddecal.type=ddecal
ddecal.maxiter=100
ddecal.tolerance=1.e-5
ddecal.propagatesolutions=True
ddecal.usemodelcolumn=True
ddecal.nchan=5
ddecal.mode=complexgain 
ddecal.h5parm=NCP-2015-01-20_annoying_source.dysco.sub.shift.avg.weights.ms.correct_shiftsolsgrid_4.h5 
ddecal.solint=69
ddecal.uvlambdamin=80.0
```

and afterwards
```
NaN/infinite data flagged in reader
===================================

Percentage of flagged visibilities detected per correlation:
  [1503571920,0,0,0] out of 1503571920 visibilities   [100%, 0%, 0%, 0%]
0 missing time slots were inserted

Total NDPPP time    2562.33 real     7117.31 user     27088.8 system
   10.5% MSReader
   92.6% DDECal ddecal.
            4.4% of it spent in predict
           93.4% of it spent in estimating gains and computing residuals
                0.00% spent in constraints
            0.0% of it spent in writing gain solutions to disk
Iterations taken: [1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1]
    0.0% MSUpdater msout.
```

Testing this now with @rvweeren's old build.

**Comment by rvweeren** [comment] 2018-11-23 13:53
> It seems somewhere during a tecandphase part all data past 5 hours are flagged

This is also related to complexgain (not tecandphase)

**Comment by rvweeren** [comment] 2018-11-23 14:01
So somewhere there is still a bug in ddecal complex gain (and maybe some other modes as well)  

(this was working in the past before NDPPP was split from the lofar build)

**Comment by aroffringa** [comment] 2018-11-23 17:48
The previous time this came because of NaNs in the DATA column. That's fixed now. Can it be that you have NaNs in the MODEL_DATA or weight column? I think that could still lead to the same problem, but if that's the case it would be easy to fix.

**Comment by tikk3r** [comment] 2018-11-23 19:51
I just checked the columns with a pyrap `getcol` and some `np.any(np.isnan(<column>))`. The DATA and CORRECTED_DATA_PHASE columns contain NaN values.

**Comment by aroffringa** [comment] 2018-11-23 19:59
Ok, but they shouldn't be a problem after the previous fix; but does MODEL_DATA or WEIGHT_SPECTRUM_SOLVE have NaNs or infs?

**Comment by tammojan** [comment] 2018-11-23 20:02
(The taql command `taql "select gntrue(isnan(MODEL_DATA)) from bla.MS"` should give you the answer to André's question efficiently.)

**Comment by rvweeren** [comment] 2018-11-23 20:03
There might be a few NaNs in here and there (but I am certain that this is a tiny tiny fraction). @tikk3r did you check the original input? (because the problem is that the complexgain bug results in NaNs, so NaNs in the output after the bug do not surprise me)

**Comment by rvweeren** [comment] 2018-11-23 20:21
@tammojan  One the original input (DATA) I get

```
    select result of 1 rows
1 selected columns:  Col_1
518998004

```

Note, the solve here used as input "DATA" as the model columns (just to H5 template solution file). So MODEL_DATA does not exist on this ms.

**Comment by rvweeren** [comment] 2018-11-23 20:30
and for the WEIGHT_SPECTRUM I get

```
    select result of 1 rows
1 selected columns:  Col_1
0

```

**Comment by rvweeren** [comment] 2018-11-23 20:31
Also I think this NaN/inf are all flagged, they are not present in the data that is used.

(because otherwise we could even not make an image)

**Comment by aroffringa** [comment] 2018-11-23 20:32
Is any of this info now for the MODEL_DATA col? You do solve from the MODEL_DATA col according to the parset, so I don't quite understand reinout's point of having no MODEL_DATA col...

The one difference that I can find is that the ~aug31 build sets any flagged data (model & input) to zero, while the new build sets the weight for flagged values to zero, sets nans to zero in the input, but doesn't set nans to zero in the model_data. So, to know whether this can be the case I'll need the MODEL_DATA info... If that's the issue it's easy to fix.

**Comment by tikk3r** [comment] 2018-11-23 20:34
The MODEL_DATA does not contain NaN values:
```python
In [4]: t = pt.table('NCP-2015-01-20_annoying_source.dysco.sub.shift.avg.weights.ms.correct_shift/')
Successful readonly open of default-locked table NCP-2015-01-20_annoying_source.dysco.sub.shift.avg.weights.ms.correct_shift/: 28 columns, 6264883 rows

In [5]: w = t.getcol('WEIGHT_SPECTRUM_SOLVE')

In [6]: import numpy as np

In [8]: np.all(np.isfinite(w))
Out[8]: True

In [9]: m = t.getcol('MODEL_DATA')

In [10]: np.all(np.isfinite(m))
Out[10]: True
```

**Comment by rvweeren** [comment] 2018-11-23 20:35
@tikk3r was talking about a later solve (where we use MODEL_DATA, which is made with WSclean btw). However I think for the purpose of debugging it is better to go the first instance where it already goes wrong. That is here:

`DPPP msin=bla.ms msin.datacolumn=DATA msout=. msin.modelcolumn=DATA steps=[ddecal] ddecal.type=ddecal ddecal.maxiter=1 ddecal.usemodelcolumn=True ddecal.nchan=1 ddecal.mode=complexgain ddecal.h5parm=bla.h5 ddecal.solint=10
`

**Comment by rvweeren** [comment] 2018-11-23 20:38
With this -first- complexgain solve (on DATA) we already get 50% of corrupted data. (the next complex gain we reach 100%, that one is one MODEL_DATA)

**Comment by aroffringa** [comment] 2018-11-23 20:39
Heh? You use the modelcolumn both as DATA and and as MODEL_DATA col? (What's the use of that?)

Ok but that then would definitely have NaNs in the ipnut model, and that would trigger the bug I was mentioning. Anyway I'll implement the fix, which should fix that first step at least, and then we'll see if it also fixes the 2nd one.

**Comment by rvweeren** [comment] 2018-11-23 20:41
(To make a template solution file where I can do some manual manipulation on)

**Comment by rvweeren** [comment] 2018-11-23 20:44
> Ok but that then would definitely have NaNs in the ipnut model,

Well, but they are flagged. I can make an image of that DATA column that looks perfectly ok (impossible to make an image if even a single NaN is present that is not flagged)

**Comment by rvweeren** [comment] 2018-11-23 20:44
Or is the bug trigged because it inputs flagged model data then?

**Comment by aroffringa** [comment] 2018-11-23 20:46
The difference between old and new is that flagged nans didn't use to be an issue, but in the new version (before the above pull request) flagged (or nanflagged) nans in the modeldata causes an issue. That should no longer be the case after ad7b5b6.

**Comment by aroffringa** [comment] 2018-11-23 20:47
btw, wsclean treats nans as flagged data, even when they are not flagged, so being able to image a set doesn't mean it doesn't have nans...

**Comment by rvweeren** [comment] 2018-11-23 20:50
Aha that makes sense of these, that commit hopefully fixes it.

**Comment by tikk3r** [comment] 2018-11-23 20:50
> The difference between old and new is that flagged nans didn't use to be an issue, but in the new version (before the above pull request) flagged (or nanflagged) nans in the modeldata causes an issue. That should no longer be the case after [ad7b5b6](https://github.com/lofar-astron/DP3/commit/ad7b5b698b1599f7ffe97b80c0f5aded4422aed7).

Thanks for that. Will test and report back.

**Closed** 2018-11-25 19:12 UTC

**Comment by tikk3r** [comment] 2018-11-27 09:35
@aroffringa @rvweeren I think it works now. After running that first DDECal step there's 9% flagged data and the time axes in the solutions run for the entire 14 hours.
