### ISSUE TITLE
Corrupt MS after gaincal usemodelcolumn=true without existing MODEL_DATA

### ISSUE THREAD

**Issue by tikk3r** [lofar-astron/DP3#119] opened 2019-02-11 13:55 UTC
Accidentally ran into this today. I tried to run `gaincal` with `usemodelcolumn=true`, but forgot to predict a model to the MODEL_DATA column. Naturally DPPP crashed, telling me it doesn't exist, but the measurement set is now corrupted, throwing

```
msoverview: Version 20110407GvD
Error: Table DataManager error: I/O error: could not read file 'target_10SB.ms/table.f8' -- is the file corrupted? -- Error occured inside the Dysco Storage Manager
```
with e.g. further DPPP commands, or msoverview. Not sure if this is an issue, or if I should just avoid solving against non-existent columns.

Using https://github.com/lofar-astron/DP3/commit/ca8faf1e11315d6840db8d75558e90ff15cafcd0, the following parset reproduces the issue for me (phase-only was done, but same result from just DATA):
```
msin = target_10SB.ms
msin.datacolumn = CORRECTED_DATA_PHASE
msout = . 
msout.datacolumn = CORRECTED_DATA_AMPPHASE
msout.storagemanager = dysco

steps = [amp]
amp.type = gaincal
amp.caltype = diagonal
amp.parmdb = selfcal_phase_ap1.h5
amp.solint = 224 
amp.nchan = 2 
amp.usemodelcolumn = True
amp.applysolution = True
```

**Comment by tammojan** [comment] 2019-06-14 08:15
I cannot reproduce this issue; closing for now (reopen if the issue reoccurs).

**Closed by tammojan** 2019-06-14 08:15 UTC
