### ISSUE TITLE
Error if compillef using -O2

### ISSUE THREAD

**Issue by AlexKurek** [lofar-astron/DP3#137] opened 2019-04-06 14:28 UTC
Dear Authors,

Im getting the following error if optimization flags  `-DCMAKE_CXX_FLAGS="-O2 -march=native -DNDEBUG"` were used:

> DEBUG   node.lof7.executable_args.Ateam_LBA_CC.skymodel: /opt/lofar/bin/makesourcedb stdout: /opt/lofar/bin/makesourcedb: Version GvD 2013-May-16
> WARNING node.lof7.executable_args.Ateam_LBA_CC.skymodel: /opt/lofar/bin/makesourcedb stderr: Caught exception: BlobIStream: getStart should be done first
> ERROR   node.lof7.executable_args: Command '/opt/lofar/bin/makesourcedb' returned non-zero exit status 1

Full LOFAR soft and BEAM are also compilled using such flags, but this is so far not causing any error.

Full log attached.
[pipeline-Pre-Facet-Calibrator-2019-04-06T14%3A14%3A15.log](https://github.com/lofar-astron/DP3/files/3050564/pipeline-Pre-Facet-Calibrator-2019-04-06T14.3A14.3A15.log)

**Comment by aroffringa** [comment] 2019-04-06 18:02
Thanks for reporting, @AlexKurek . This is a know issue, described in #109. The cause is `-DNDEBUG`. I don't know why exactly, someone would have to analyze the problem more carefully. When I discovered optimizations weren't turned on, I did add `-O3` and `-march=native` manually in #107 ( 31fc93e ), so most of the optimizations are always turned on. I'll close this bug, if you want to comment further please use #109 .

**Closed by aroffringa** 2019-04-06 18:02 UTC
